services:

  postgres-db:
    container_name: cv-postgres
    image: postgres:alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 3636
    volumes:
      - cv-volume:/var/lib/postgresql/data
    ports:
      - "5436:5432"
    networks:
      - cv_nerwork
    restart: unless-stopped

  backend-app:
    container_name: cv-maker
    build: 
      context: .
    networks:
      - cv_nerwork
    ports:
      - "3000:3000"
    depends_on:
      - postgres-db

networks:
  cv_nerwork:
    driver: bridge

volumes:
  cv-volume:
